### ISSUE TITLE
SOCKS proxy support

### ISSUE THREAD

**Issue by ofry** [romjacket/skeletonKey#1]
Could you add SOCKS (SOCKS4, SOCKS5) proxy support?

For example, I can get some proxies from http://hideme.ru/proxy-list/?type=45#list

So SkeletonKey should try to access archive.org/download through these proxies.

Example of config file.

IP:port type
127.0.0.1:80 SOCKS4

or same...

**Comment by romjacket** [comment]
Archive.org is important and I want everyone to be able to use it.  I can allow skeletonKey to toggle your windows proxy settings when downloading from archive.org.  Would this be acceptable?

**Comment by ofry** [comment]
Hm... this option will be great as "first step".

Just because I HAVEN'T set windows proxy settings...

And free proxies is slow and unstable. So it's good to have "proxy manager", at least *.ini.

**Comment by ofry** [comment]
Hm... this option will be great as "first step".

Just because I HAVEN'T set windows proxy settings...

And free proxies is slow and unstable. So it's good to have "proxy manager", at least *.ini.
