### ISSUE TITLE
Parsed and corrected DATs

### ISSUE THREAD

**Issue by Asnivor** [romjacket/skeletonKey#1]
Hey dude, 

I finished parsing all the xml files:

https://github.com/Asnivor/AsniSkeletonKeyDB/tree/master/SKDB/SKDB/ExportedDats

There were a few that got skipped that you will probably have to dig out and correct manually. Other than that it seemed to go pretty well.

I wasn't sure if the way you parse XML tags is case-sensitive or not, so I just went with what you have there already. More details in the link above.

**Comment by romjacket** [comment]
THESE ARE GREAT!!! Thanks for renumbering them too. That was going to take
a while.
